language: ruby
rvm:
- 2.5
before_install:
  - gem uninstall bundler
  - gem install bundler --version '1.16.1'
install: "bundle install"
script: "bundle exec jekyll build"
sudo: false
cache: bundler
exclude: [vendor]
email: false
