# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://batchofcode.com" # the base hostname & protocol for your site
exclude: [vendor]
gems: [jekyll-paginate]
# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Batch of Code
  avatar: avatar.jpg
  gravatar: "61ac87388e3c30fd7c0a1551f59b9040"
  description: "Musings on software, hardware, and anything in between by Ryan Batchelder." # used by search engines

  # Header and footer text
  header_text: >
     <p>Hi, I'm Ryan Batchelder.</p>

  header_text_feature_image:
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a> Copyright Ryan Batchelder

  # Icons
  rss: false
  email_address: "ryanbatch@gmail.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "rdbatch02"
  google_plus:
  instagram:
  linkedin: https://www.linkedin.com/in/rdbatch02/
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "rdbatch02"
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-22474755-2"
  disqus_shortname: "batchofcode"
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
